// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpaceTaxesCalculator.Data;

namespace SpaceTaxesCalculator.Migrations
{
    [DbContext(typeof(TaxCalculatorDbContext))]
    [Migration("20220104232402_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TaxCalculator.Data.Models.Spaceship", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("InitialTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("MilesTraveled")
                        .HasColumnType("bigint");

                    b.Property<int>("PurchaseYear")
                        .HasColumnType("int");

                    b.Property<int>("TaxCalculationYear")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxDue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Spaceships");
                });
#pragma warning restore 612, 618
        }
    }
}
